shiny:
  image:
    repository: ghcr.io/arnaud-feldmann/sirene-shinygouv-idf
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    hostname: sirene-shinygouv-idf.lab.sspcloud.fr
  s3:
    enabled: false
  postgresql:
    enabled: false
  resources: {}
  probes:
    exec:
      command:
      - exit $(test $(date +%d) -eq 6 && echo 1 || echo 0)
    failureThreshold: 1
    initialDelaySeconds: 90000
