name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/arnaud-feldmann/sirene-shinygouv-idf:${{ steps.date.outputs.date }} --tag ghcr.io/arnaud-feldmann/sirene-shinygouv-idf:latest
        docker push ghcr.io/arnaud-feldmann/sirene-shinygouv-idf --all-tags
